### ISSUE TITLE
Allow habits to have interval larger than 99 days

### ISSUE THREAD

**Issue by akhater** [iSoron/uhabits#192]
I have a task that needs to be done every 4 months but the max time I can enter in the flexible schedule is 99 days :)

thanks

**Comment by aleksejrs** [comment]
I also have such a task (although 4 months is the absolute maximum).

**Comment by akhater** [comment]
Hi Aleksejrs 

I'm interested why would you consider 4 months as absolute maximum ? is it from a technical perspective or you do you mean that this is no longer called a habit :)

**Comment by aleksejrs** [comment]
It's not a habit; some companies require specific usage actions to happen at least that often.

**Comment by iSoron** [comment]
Thank you for the suggestion, @akhater. The limit is there because I didn't expect anyone to have habits with such long intervals, but there is no technical reason why these should not be allowed.

Implementation: We just need to increase the maximum length of the text field from 2 to 3 characters. I think 999 is a reasonable upper limit.

**Comment by iSoron** [comment]
Fixed by 10131d5.

**Comment by akhater** [comment]
Thank you

**Comment by tilt-me** [comment]
Seems this issue is back with version 2.0.1: now it is not possibile to set an interval > 99 days:  @iSoron  could you please restore the 3-char limit?  
Thanks in advance, bye!

**Comment by palashkulsh** [comment]
this issue seems to have resurfaced

**Comment by neube3** [comment]
The limit seems to still be at 999.

It's still an arbitrary limit, why not a bigger one? The app is used for remembering about health and medical check-ups can often have more than 999 days between them required (e.g. once every 1825 days/5 years" - checking for Lyme disease markers, cancer screenings, etc.).

While 99999 days (273 years) seems pretty overkill, who's to say the human lifespan won't extend that much in the next 40 years of us using the app?
